import { colors } from './colors'
import { radius } from './radius'
import { spacing } from './spacing'

export const sizes = {
  ring: 136,
  ringStroke: 8,
  ringTick: 6,
  spinnerSm: '1rem',
  spinnerMd: '1.375rem',
  spinnerLg: '1.75rem',
  iconLg: '2rem',
  contentWidthSm: '18rem',
  contentWidthMd: '22rem',
  contentWidthLg: '24rem',
  voiceMicWrap: '7rem',
  voiceMicButton: '5rem',
  paperMaxHeight: 320,
  touchMinHeight: 48,
  inputMinHeight: 48,
  focusRingWidth: 3,
  borderDefault: 1.5,
  borderStrong: 2,
  borderAccent: 3,
} as const

export const opacity = {
  hidden: 0,
  subtle: 0.3,
  muted: 0.6,
  soft: 0.7,
  strong: 1,
  skeletonStep: 0.1,
} as const

export const motion = {
  durationFast: '150ms',
  durationNormal: '220ms',
  durationSlow: '600ms',
  easingStandard: 'ease',
  easingRing: 'cubic-bezier(0.4, 0, 0.2, 1)',
  animationSlideUp: 'slideUp 0.22s ease',
} as const

export const shadows = {
  xs: '0 1px 3px rgba(0, 0, 0, 0.3)',
  sm: '0 1px 4px rgba(0, 0, 0, 0.35), 0 1px 2px rgba(0, 0, 0, 0.2)',
  md: '0 4px 16px rgba(0, 0, 0, 0.4), 0 2px 6px rgba(0, 0, 0, 0.2)',
  overlayButton: `0 0 0 ${sizes.focusRingWidth}px ${colors.whiteTransparent12}`,
} as const

export const borders = {
  panel: `${sizes.borderDefault}px solid ${colors.dividerSoft}`,
  input: `${sizes.borderDefault}px solid ${colors.dividerFocus}`,
  inputHover: `${sizes.borderDefault}px solid ${colors.dividerHover}`,
  overlayGhost: `${sizes.borderDefault}px solid ${colors.whiteTransparent30}`,
  overlayButton: `${sizes.borderDefault}px solid ${colors.whiteTransparent25}`,
  accent: `${sizes.borderAccent}px solid`,
} as const

export const zIndex = {
  floating: 50,
  modal: 100,
  overlay: 200,
} as const

export const cssVarTokens = {
  '--token-color-bg': colors.background,
  '--token-color-surface': colors.surface,
  '--token-color-surface-alt': colors.surfaceAlt,
  '--token-color-surface-muted': colors.surfaceMuted,
  '--token-color-text-primary': colors.textPrimary,
  '--token-color-text-secondary': colors.textSecondary,
  '--token-color-text-tertiary': colors.textTertiary,
  '--token-color-positive': colors.positive,
  '--token-color-positive-dark': colors.positiveDark,
  '--token-color-positive-light': colors.positiveLight,
  '--token-color-positive-ghost': colors.positiveGhost,
  '--token-color-positive-muted': '#3d8b6e',
  '--token-color-positive-hover': '#0d5e42',
  '--token-color-negative': colors.negative,
  '--token-color-negative-dark': colors.negativeDark,
  '--token-color-negative-light': colors.negativeLight,
  '--token-color-negative-ghost': colors.negativeGhost,
  '--token-color-negative-border': '#5c1a1a',
  '--token-color-negative-text': '#fca5a5',
  '--token-color-negative-soft': '#7f2222',
  '--token-color-info': colors.info,
  '--token-color-info-dark': colors.infoDark,
  '--token-color-info-light': colors.infoLight,
  '--token-color-info-hover': '#1e3a6e',
  '--token-color-warning': colors.warning,
  '--token-color-warning-light': '#3d2e0a',
  '--token-color-white': colors.white,
  '--token-color-white-transparent-12': colors.whiteTransparent12,
  '--token-color-white-transparent-20': colors.whiteTransparent20,
  '--token-color-white-transparent-25': colors.whiteTransparent25,
  '--token-color-white-transparent-30': colors.whiteTransparent30,
  '--token-color-white-transparent-40': colors.whiteTransparent40,
  '--token-color-white-transparent-50': colors.whiteTransparent50,
  '--token-color-white-transparent-70': colors.whiteTransparent70,
  '--token-color-divider': colors.divider,
  '--token-color-divider-soft': colors.dividerSoft,
  '--token-color-divider-focus': colors.dividerFocus,
  '--token-color-divider-hover': colors.dividerHover,
  '--token-color-overlay': colors.overlay,
  '--token-color-overlay-clear': 'rgba(0, 0, 0, 0)',
  '--token-color-overlay-strong': colors.overlayStrong,
  '--token-space-xs': `${spacing.xs}px`,
  '--token-space-sm': `${spacing.sm}px`,
  '--token-space-md': `${spacing.md}px`,
  '--token-space-lg': `${spacing.lg}px`,
  '--token-space-xl': `${spacing.xl}px`,
  '--token-space-xxl': `${spacing.xxl}px`,
  '--token-space-xxxl': `${spacing.xxxl}px`,
  '--token-space-page-x': `${spacing.pageX}px`,
  '--token-space-page-top': `${spacing.pageTop}px`,
  '--token-space-page-bottom': `${spacing.pageBottom}px`,
  '--token-radius-sm': `${radius.sm}px`,
  '--token-radius-md': `${radius.md}px`,
  '--token-radius-lg': `${radius.lg}px`,
  '--token-radius-pill': `${radius.pill}px`,
  '--token-size-content-sm': sizes.contentWidthSm,
  '--token-size-content-md': sizes.contentWidthMd,
  '--token-size-content-lg': sizes.contentWidthLg,
  '--token-size-voice-mic-wrap': sizes.voiceMicWrap,
  '--token-size-voice-mic-button': sizes.voiceMicButton,
  '--token-shadow-xs': shadows.xs,
  '--token-shadow-sm': shadows.sm,
  '--token-shadow-md': shadows.md,
  '--token-shadow-modal': '0 -4px 32px rgba(0, 0, 0, 0.4)',
  '--token-shadow-positive': '0 2px 12px rgba(10, 146, 99, 0.35)',
  '--token-shadow-positive-hover': '0 4px 18px rgba(10, 146, 99, 0.45)',
  '--token-shadow-info': '0 2px 12px rgba(37, 99, 235, 0.3)',
  '--token-shadow-negative': '0 2px 10px rgba(220, 38, 38, 0.3)',
  '--token-shadow-positive-glow': '0 4px 28px rgba(10, 146, 99, 0.6)',
  '--token-shadow-floating-primary': 'inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 4px 24px rgba(10, 146, 99, 0.4), 0 1px 4px rgba(10, 146, 99, 0.25)',
  '--token-shadow-floating-primary-hover': 'inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 6px 32px rgba(10, 146, 99, 0.5), 0 2px 8px rgba(10, 146, 99, 0.3)',
  '--token-z-floating': String(zIndex.floating),
  '--token-z-modal': String(zIndex.modal),
  '--token-z-overlay': String(zIndex.overlay),
} as const

export const uiTokens = {
  animation: {
    itemDelayMs: 30,
    historyItemDelayMs: 50,
  },
  opacity: {
    skeletonMedium: opacity.muted,
    skeletonLight: opacity.subtle,
    timelineSkeletonTail: opacity.subtle,
  },
  borderLeftWidth: `${sizes.borderAccent}px`,
  confirmPanelPadding: `${spacing.lg}px`,
  reviewPanelPadding: `${spacing.lg}px`,
  reviewPanelMaxHeight: '50dvh',
  voicePanelMaxWidth: sizes.contentWidthLg,
  voiceSilenceTimeoutMs: 3500,
  voiceMaxDurationMs: 15000,
} as const
